# -*- coding: utf-8 -*-
"""Main_Model+Ablation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thOdcK9pxWJe-Y6XsPhxPLRr7HxRgzdT


!unrar x /content/新建文件夹.rar

"""# 导入python包"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from PIL import Image
import seaborn as sns

from tokenizers import Tokenizer
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch
from torch import nn
from torch.nn import  functional as F

from torchvision.io import read_image
from torchvision import datasets
from torchvision.transforms import ToTensor
from torchvision import transforms
import torchvision


from torchvision import datasets,models

from transformers import AutoTokenizer, AutoModelForSequenceClassification

"""# 超参数定义"""

max_len = 40
n_class = 4
train_num = 160
test_num = 40





"""# 准备数据集"""



"""## 生成训练集和测试集"""

def get_pic_name(item):
  pic_name = item.split('/')[-1]
  pic_path = '/content/新建文件夹/'+pic_name
  return pic_path

import json
import re

def get_num_list(json_str):
  # json_str = "{'score': [0.1, 0.7, 0.2]}"
  ori_list = json_str.split('[')[1].split(']')[0].split(',')
  num_list = [float(item) for item in ori_list]
  return num_list

pd_all = pd.read_csv('/content/新建文件夹/加了score值的表格.csv').sample(frac=1).reset_index(drop=True)
pd_all['label'] = pd_all['label'] - 1
pd_all['pic_path'] = pd_all['pic'].map(get_pic_name)
pd_all['vec'] = pd_all.score.map(get_num_list)
pd_train = pd_all[:160]
pd_test = pd_all[160:]
pd_all

# pd_all = pd.read_csv('/content/数据集/data.csv',encoding='gbk').sample(frac=1).reset_index(drop=True)
# pd_all['pic_path'] = pd_all['pic'].map(get_pic_name)
# pd_all['vec'] = [[0.5,0.1,0.4]]*len(pd_all)
# pd_train = pd_all[:160]
# pd_test = pd_all[160:]
# pd_all

"""## 查看图文特征"""

eg_pic_path = '/content/新建文件夹/91.jpg'
# eg_pic_path = img_dir + '16_05_01_100.jpg'
# 打开图像并加载
img = Image.open(eg_pic_path)
# 显示图像
img

def get_len(item):
  sen_len = len(item.split(' '))
  return sen_len

pd_train['len'] = pd_train['text'].map(len)
pd_test['len'] = pd_test['text'].map(len)
pd_train

pd_train['len'].hist()

pd_train['label'].value_counts()

pd_test['label'].value_counts()



"""# 确定GPU cpu使用情况"""

# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using {device} device")





"""# Gemini-Scene模型： vit + bert + clip + att"""



"""## 准备训练和测试循环"""



def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (x_img,x_img_clip, x_text,x_text_clip, x_vec, y) in enumerate(dataloader):

        x_img, x_text, y = x_img.to(device),x_text.to(device), y.to(device)
        x_img_clip,x_text_clip = x_img_clip.to(device),x_text_clip.to(device)
        x_vec = x_vec.to(device)
        pred = model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 30 == 0:
            loss, current = loss.item(), batch * len(x_img)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for batch, (x_img,x_img_clip, x_text,x_text_clip, x_vec,  y) in enumerate(dataloader):
            x_img, x_text, y = x_img.to(device),x_text.to(device), y.to(device)
            x_img_clip,x_text_clip = x_img_clip.to(device),x_text_clip.to(device)
            x_vec = x_vec.to(device)
            pred = model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss, correct

"""## 数据处理和特征工程"""





"""### 英文编码tokenizer roberta"""

model_name = "bert-base-chinese"
tokenizer_bert = AutoTokenizer.from_pretrained(model_name)



eg_text = '早上好'
eg_result = tokenizer_bert(eg_text, padding='max_length', max_length=25, truncation=True, return_tensors="pt")
eg_result

voc_size = tokenizer_bert.vocab_size
voc_size



"""### clip 文本处理"""

from transformers import AutoTokenizer, CLIPTextModelWithProjection

t_clip_model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
t_clip_tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

# inputs = t_clip_tokenizer(["a photo of a cat", "a photo of a dog"],  return_tensors="pt",max_length=50,padding="max_length",truncation=True)
inputs = t_clip_tokenizer("a photo of a cat",  return_tensors="pt",max_length=50,padding="max_length",truncation=True)

outputs = t_clip_model(**inputs)
text_embeds = outputs.text_embeds

text_embeds.shape



inputs

t_clip_model(inputs.input_ids).text_embeds

"""### clip 图像处理"""

from PIL import Image
import requests
from transformers import AutoProcessor, CLIPVisionModelWithProjection

img_clip_model = CLIPVisionModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
img_clip_processor = AutoProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = img_clip_processor(images=image, return_tensors="pt")

outputs = img_clip_model(**inputs)
image_embeds = outputs.image_embeds

inputs.pixel_values.shape

outputs.image_embeds.shape

pd_all.head()

"""### 准备dataset"""

class CustomDataset(Dataset):
    def __init__(self, pd_data,tokenizer_en):
        self.pd_data = pd_data
        self.text_list = list(pd_data['text'])
        self.label_list = list(pd_data['label'])
        self.img_path_list = list(pd_data['pic_path'])
        self.vec_lists = list(pd_data['vec'])
        self.tokenizer = tokenizer_en
        self.t_clip_tokenizer = t_clip_tokenizer
        self.img_clip_processor = img_clip_processor

    def __len__(self):
        return len(self.pd_data)

    def __getitem__(self, idx):


        # 文本数据处理
        one_text = self.text_list[idx]
        one_text_array = self.tokenizer(one_text, padding='max_length', max_length=max_len, truncation=True, return_tensors="pt")['input_ids'][0]
        one_clip_text = self.t_clip_tokenizer(one_text,  return_tensors="pt",max_length=max_len,padding="max_length",truncation=True)['input_ids'][0]


        # 图像数据处理
        one_path = self.img_path_list[idx]
        # one_path = img_dir + one_path
        img_tensor = read_image(one_path,mode=torchvision.io.ImageReadMode.RGB)
        img_tensor = transforms.Resize((224,224))(img_tensor).float()

        image = Image.open(one_path).convert("RGB")
        one_clip_img = img_clip_processor(images=image, return_tensors="pt").pixel_values[0]


        # 向量数据处理
        one_vec = self.vec_lists[idx]
        one_vec_tensor = torch.tensor(one_vec).float()


        # label数据处理
        one_label = self.label_list[idx]
        one_label = torch.tensor(one_label).long()
        return img_tensor, one_clip_img, one_text_array, one_clip_text, one_vec_tensor, one_label


tran_ds = CustomDataset(pd_train[:train_num],tokenizer_bert)
test_ds = CustomDataset(pd_test[:test_num],tokenizer_bert)

tran_ds[1][0].shape,tran_ds[1][1].shape,len(tran_ds),len(test_ds)

"""### 准备dataloader"""



train_dl = DataLoader(tran_ds, batch_size=10, shuffle=True)
test_dl = DataLoader(test_ds, batch_size=8)

len(test_dl.dataset)

for b_img,b_img_clip, b_text,b_text_clip,b_vec,label in test_dl:
  print(b_text.shape)
  print(b_img.shape)
  print(b_text_clip.shape)
  print(b_img_clip.shape)
  print(b_vec.shape)
  print(label)
  break

b_vec

"""## 模型构建

### vit模块
"""

class Image_vit(nn.Module):
    def __init__(self):
        super().__init__()
        self.base_model_vit = models.vit_b_16(pretrained=True)
        self.base_model_vit.heads.head = nn.Linear(768, 100)

    def forward(self, x):
        x = self.base_model_vit(x)
        return x

vit_block = Image_vit().to(device)
# print(img_block)
vit_block(b_img.to(device)).shape

"""### 文本数据处理"""



class textBert(nn.Module):
    def __init__(self,):
        super().__init__()
        self.model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=100).to(device)

    def forward(self, x):
        x = self.model(x)
        return x.logits
text_bert = textBert().to(device)

text_bert(b_text.to(device)).shape

"""### 结构化数据处理"""

class vecBlock(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3, 120)
        self.fc2 = nn.Linear(120, 100)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x


vec_block = vecBlock().to(device)
print(vec_block)
vec_block(b_vec.to(device)).shape

"""### 整体模型构建"""

# Define model
class bigModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.img_block = Image_vit()
        self.text_block = textBert()
        self.vec_block = vecBlock()

        self.img_clip_model = img_clip_model
        self.t_clip_model = t_clip_model
        self.relu = nn.ReLU()
        self.lin1 = nn.Linear(600, 50)
        self.lin2 = nn.Linear(50, n_class)
        self.lin_t = nn.Linear(512, 100)
        self.lin_i = nn.Linear(512, 100)
        self.att = nn.TransformerEncoderLayer(d_model=100,nhead=2)

    def forward(self, img,img_clip,text,text_clip,vec):
        x1 = self.img_block(img)
        x4_img_clip = self.img_clip_model(img_clip).image_embeds
        x4_img_clip = self.lin_i(x4_img_clip)

        x2 = self.text_block(text)
        x5_t_clip = self.t_clip_model(text_clip).text_embeds
        x5_t_clip = self.lin_t(x5_t_clip)

        x3 = self.vec_block(vec)

        x = torch.stack([x1,x2,x4_img_clip,x5_t_clip,x3],dim=1)
        x = self.att(x)

        x = self.flatten(x)

        x = torch.cat([x,x1],dim=1)
        x = self.lin1(x)
        x = self.lin2(x)
        # x =
        return x
big_model = bigModel().to(device)
big_model(b_img.to(device),b_img_clip.to(device),b_text.to(device),b_text_clip.to(device),b_vec.to(device)).shape





"""## 准备损失函数和优化器"""

loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
optimizer = torch.optim.Adam(big_model.parameters(), lr=2e-5)

"""## 训练和测试"""

epochs = 3
train_loss_list = []
train_acc_list = []
test_loss_list = []
test_acc_list = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dl, big_model, loss_fn, optimizer)

    train_loss, train_correct = test(train_dl, big_model, loss_fn)
    test_loss, test_correct = test(test_dl, big_model, loss_fn)
    train_loss_list.append(train_loss)
    train_acc_list.append(train_correct)
    test_loss_list.append(test_loss)
    test_acc_list.append(test_correct)
print("Done!")



"""## 可视化训练过程"""

# train_loss_array,train_acc_array,val_loss_array,val_acc_array
acc = train_acc_list
val_acc = test_acc_list

loss = train_loss_list
val_loss = test_loss_list
epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""## 统计指标分析"""



"""### 模型验证集预测"""

predict_list = []
label_list = []
predict_pro_list = []
m_softmax = nn.Softmax(dim=1)
for x_img,x_img_clip, x_text,x_text_clip, x_vec,  y in test_dl:
  x_img,x_img_clip, x_text,x_text_clip,x_vec,  y = x_img.to(device),x_img_clip.to(device),x_text.to(device),x_text_clip.to(device), x_vec.to(device), y.to(device)

  # Compute prediction error
  # print(x_img.shape,x_text.shape)
  predict_score = big_model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
  # predict_score = big_model(b_img,b_text)
  predict_pro = m_softmax(predict_score)

  predict_label = np.argmax(predict_score.detach().cpu().numpy(),axis=1)

  predict_pro_list.append(predict_pro.detach().cpu().numpy())
  predict_list.append(predict_label)
  label_list.append(y.detach().cpu().numpy())

predict_pro_array = np.vstack(predict_pro_list)[:,1]
predict_array = np.hstack(predict_list)
label_array = np.hstack(label_list)
predict_pro_array[:5],predict_array[:5],label_array[:5]

np.unique(predict_array)

len(np.unique(label_array))



"""### 分类报告"""

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(label_array, predict_array,digits=3))



"""### 混淆矩阵"""



from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(label_array, predict_array)
cnf_matrix



sns.heatmap(cnf_matrix, annot=True, fmt='g')

cm_normalized = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_normalized, annot=True, fmt='.3f')



"""# 消融实验模型"""



"""## 准备训练和测试循环"""



def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (x_img, x_text, x_vec,  y) in enumerate(dataloader):
        x_img, x_text,x_vec,  y = x_img.to(device),x_text.to(device), x_vec.to(device), y.to(device)

        # Compute prediction error
        # print(x_img.shape,x_text.shape)
        pred = model(x_img, x_text, x_vec)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 30 == 0:
            loss, current = loss.item(), batch * len(x_img)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for batch, (x_img, x_text, x_vec,  y) in enumerate(dataloader):
            x_img, x_text,x_vec,  y = x_img.to(device),x_text.to(device), x_vec.to(device),y.to(device)
            pred = model(x_img, x_text, x_vec)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss, correct

"""## 数据处理和特征工程"""



"""### 英文编码tokenizer"""

# tokenizer_en = Tokenizer.from_pretrained("bert-base-uncased")
model_name = "bert-base-uncased"
tokenizer_bert = AutoTokenizer.from_pretrained(model_name)



eg_text = '$T$ triumphs at Manchester May Day Festival'
eg_result = tokenizer_bert(eg_text, padding='max_length', max_length=25, truncation=True, return_tensors="pt")
eg_result

voc_size = tokenizer_bert.vocab_size
voc_size

"""### 准备dataset"""

pd_all.head()

class CustomDataset(Dataset):
    def __init__(self, pd_data,tokenizer_en):
        self.pd_data = pd_data
        self.text_list = list(pd_data['text'])
        self.label_list = list(pd_data['label'])
        self.img_path_list = list(pd_data['pic_path'])
        self.vec_lists = list(pd_all['vec'])
        self.tokenizer = tokenizer_en

    def __len__(self):
        # return len(self.label_list)
        return len(self.pd_data)

    def __getitem__(self, idx):
        # 文本数据处理
        one_text = self.text_list[idx]
        one_text_array = self.tokenizer(one_text, padding='max_length', max_length=max_len, truncation=True, return_tensors="pt")['input_ids'][0]

        # 图像数据处理
        one_path = self.img_path_list[idx]
        # one_path = img_dir + one_path
        img_tensor = read_image(one_path,mode=torchvision.io.ImageReadMode.RGB)
        img_tensor = transforms.Resize((224,224))(img_tensor).float()

        # 向量数据处理
        one_vec = self.vec_lists[idx]
        one_vec_tensor = torch.tensor(one_vec).float()


        # label数据处理
        one_label = self.label_list[idx]
        one_label = torch.tensor(one_label).long()
        return img_tensor,one_text_array,one_vec_tensor, one_label


tran_ds = CustomDataset(pd_train[:train_num],tokenizer_bert)
test_ds = CustomDataset(pd_test[:test_num],tokenizer_bert)

tran_ds[1][0].shape,tran_ds[1][1].shape,len(tran_ds),len(test_ds)

pd_train.head()

"""### 准备dataloader"""



train_dl = DataLoader(tran_ds, batch_size=10, shuffle=True)
test_dl = DataLoader(test_ds, batch_size=8)

len(test_dl.dataset)

for b_img,b_text,b_vec,label in test_dl:
  print(b_text.shape)
  print(b_img.shape)
  print(b_vec.shape)
  print(label)
  break

"""## 模型构建

### 图像数据处理
"""

import torch.nn as nn
import torch.nn.functional as F


class ImageBlock(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(44944, 120)
        self.fc2 = nn.Linear(120, 100)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x


img_block = ImageBlock().to(device)
print(img_block)
img_block(b_img.to(device)).shape

"""### 文本数据处理"""



class textCNN(nn.Module):
    def __init__(self,):
        super().__init__()
        emb_dim = 100
        n_class = 2
        kernels=[3,4,5]
        kernel_number=[150,150,150]
        self.embd = nn.Embedding(voc_size, emb_dim)
        self.convs = nn.ModuleList([nn.Conv1d(max_len, number, size,padding=size) for (size,number) in zip(kernels,kernel_number)])
        self.dropout=nn.Dropout(0.1)
        self.out = nn.Linear(sum(kernel_number), 100)

    def forward(self, x):
        x = self.embd(x)

        x = [F.relu(conv(x)) for conv in self.convs]
        x = [F.max_pool1d(i, i.size(2)).squeeze(2) for i in x]
        x = torch.cat(x, 1)
        x = self.dropout(x)
        x = self.out(x)
        return x
text_cnn = textCNN().to(device)
# text_cnn(text)[0].shape,text_cnn(text)[1].shape,text_cnn(text)[2].shape

text_cnn(b_text.to(device)).shape

"""### 结构化数据处理"""

class vecBlock(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3, 120)
        self.fc2 = nn.Linear(120, 100)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x


vec_block = vecBlock().to(device)
print(vec_block)
vec_block(b_vec.to(device)).shape

"""### 整体模型构建"""

# Define model
class bigModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.img_block = ImageBlock()
        self.text_block = textCNN()
        self.vec_block = vecBlock()
        self.relu = nn.ReLU()
        self.lin1 = nn.Linear(300, 50)
        self.lin2 = nn.Linear(50, n_class)


    def forward(self, img,text,vec):
        x1 = self.img_block(img)
        x2 = self.text_block(text)
        x3 = self.vec_block(vec)

        x = torch.cat([x1,x2,x3],dim=1)
        x = self.flatten(x)
        x = self.lin1(x)
        x = self.lin2(x)
        # x =
        return x
big_model = bigModel().to(device)
big_model(b_img.to(device),b_text.to(device),b_vec.to(device))





"""## 准备损失函数和优化器"""

loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
optimizer = torch.optim.Adam(big_model.parameters(), lr=1e-3)

"""## 训练和测试"""

epochs = 3
train_loss_list = []
train_acc_list = []
test_loss_list = []
test_acc_list = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dl, big_model, loss_fn, optimizer)

    train_loss, train_correct = test(train_dl, big_model, loss_fn)
    test_loss, test_correct = test(test_dl, big_model, loss_fn)
    train_loss_list.append(train_loss)
    train_acc_list.append(train_correct)
    test_loss_list.append(test_loss)
    test_acc_list.append(test_correct)
print("Done!")



"""## 可视化训练过程"""

# train_loss_array,train_acc_array,val_loss_array,val_acc_array
acc = train_acc_list
val_acc = test_acc_list

loss = train_loss_list
val_loss = test_loss_list
epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""## 统计指标分析"""



"""### 模型验证集预测"""

predict_list = []
label_list = []
predict_pro_list = []
m_softmax = nn.Softmax(dim=1)
for x_img, x_text, x_vec,  y in test_dl:
  x_img, x_text,x_vec,  y = x_img.to(device),x_text.to(device), x_vec.to(device), y.to(device)

  # Compute prediction error
  # print(x_img.shape,x_text.shape)
  predict_score = big_model(x_img, x_text, x_vec)
  # predict_score = big_model(b_img,b_text)
  predict_pro = m_softmax(predict_score)

  predict_label = np.argmax(predict_score.detach().cpu().numpy(),axis=1)

  predict_pro_list.append(predict_pro.detach().cpu().numpy())
  predict_list.append(predict_label)
  label_list.append(y.detach().cpu().numpy())

predict_pro_array = np.vstack(predict_pro_list)[:,1]
predict_array = np.hstack(predict_list)
label_array = np.hstack(label_list)
predict_pro_array[:5],predict_array[:5],label_array[:5]

np.unique(predict_array)

len(np.unique(label_array))



"""### 分类报告"""

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(label_array, predict_array,digits=3))



"""### 混淆矩阵"""



from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(label_array, predict_array)
cnf_matrix



sns.heatmap(cnf_matrix, annot=True, fmt='g')

cm_normalized = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_normalized, annot=True, fmt='.3f')





"""# 消融实验模型二： vit+cnn"""







"""## 准备训练和测试循环"""



def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (x_img, x_text, x_vec,  y) in enumerate(dataloader):
        x_img, x_text,x_vec,  y = x_img.to(device),x_text.to(device), x_vec.to(device), y.to(device)

        # Compute prediction error
        # print(x_img.shape,x_text.shape)
        pred = model(x_img, x_text, x_vec)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 30 == 0:
            loss, current = loss.item(), batch * len(x_img)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for batch, (x_img, x_text, x_vec,  y) in enumerate(dataloader):
            x_img, x_text,x_vec,  y = x_img.to(device),x_text.to(device), x_vec.to(device),y.to(device)
            pred = model(x_img, x_text, x_vec)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss, correct

"""## 数据处理和特征工程"""



"""### 英文编码tokenizer"""

# tokenizer_en = Tokenizer.from_pretrained("bert-base-uncased")
model_name = "bert-base-uncased"
tokenizer_bert = AutoTokenizer.from_pretrained(model_name)



eg_text = '$T$ triumphs at Manchester May Day Festival'
eg_result = tokenizer_bert(eg_text, padding='max_length', max_length=25, truncation=True, return_tensors="pt")
eg_result

voc_size = tokenizer_bert.vocab_size
voc_size

"""### 准备dataset"""

pd_all.head()

class CustomDataset(Dataset):
    def __init__(self, pd_data,tokenizer_en):
        self.pd_data = pd_data
        self.text_list = list(pd_data['text'])
        self.label_list = list(pd_data['label'])
        self.img_path_list = list(pd_data['pic_path'])
        self.vec_lists = list(pd_all['vec'])
        self.tokenizer = tokenizer_en

    def __len__(self):
        # return len(self.label_list)
        return len(self.pd_data)

    def __getitem__(self, idx):
        # 文本数据处理
        one_text = self.text_list[idx]
        one_text_array = self.tokenizer(one_text, padding='max_length', max_length=max_len, truncation=True, return_tensors="pt")['input_ids'][0]

        # 图像数据处理
        one_path = self.img_path_list[idx]
        # one_path = img_dir + one_path
        img_tensor = read_image(one_path,mode=torchvision.io.ImageReadMode.RGB)
        img_tensor = transforms.Resize((224,224))(img_tensor).float()

        # 向量数据处理
        one_vec = self.vec_lists[idx]
        one_vec_tensor = torch.tensor(one_vec).float()


        # label数据处理
        one_label = self.label_list[idx]
        one_label = torch.tensor(one_label).long()
        return img_tensor,one_text_array,one_vec_tensor, one_label


tran_ds = CustomDataset(pd_train[:train_num],tokenizer_bert)
test_ds = CustomDataset(pd_test[:test_num],tokenizer_bert)

tran_ds[1][0].shape,tran_ds[1][1].shape,len(tran_ds),len(test_ds)

pd_train.head()

"""### 准备dataloader"""



train_dl = DataLoader(tran_ds, batch_size=10, shuffle=True)
test_dl = DataLoader(test_ds, batch_size=8)

len(test_dl.dataset)

for b_img,b_text,b_vec,label in test_dl:
  print(b_text.shape)
  print(b_img.shape)
  print(b_vec.shape)
  print(label)
  break

"""## 模型构建

### 图像数据处理
"""

import torch.nn as nn
import torch.nn.functional as F


class Image_vit(nn.Module):
    def __init__(self):
        super().__init__()
        self.base_model_vit = models.vit_b_16(pretrained=True)
        self.base_model_vit.heads.head = nn.Linear(768, 100)

    def forward(self, x):
        x = self.base_model_vit(x)
        return x

img_block = Image_vit().to(device)
# print(img_block)
img_block(b_img.to(device)).shape

"""### 文本数据处理"""



class textCNN(nn.Module):
    def __init__(self,):
        super().__init__()
        emb_dim = 100
        n_class = 2
        kernels=[3,4,5]
        kernel_number=[150,150,150]
        self.embd = nn.Embedding(voc_size, emb_dim)
        self.convs = nn.ModuleList([nn.Conv1d(max_len, number, size,padding=size) for (size,number) in zip(kernels,kernel_number)])
        self.dropout=nn.Dropout(0.1)
        self.out = nn.Linear(sum(kernel_number), 100)

    def forward(self, x):
        x = self.embd(x)

        x = [F.relu(conv(x)) for conv in self.convs]
        x = [F.max_pool1d(i, i.size(2)).squeeze(2) for i in x]
        x = torch.cat(x, 1)
        x = self.dropout(x)
        x = self.out(x)
        return x
text_cnn = textCNN().to(device)
# text_cnn(text)[0].shape,text_cnn(text)[1].shape,text_cnn(text)[2].shape

text_cnn(b_text.to(device)).shape

"""### 结构化数据处理"""

class vecBlock(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3, 120)
        self.fc2 = nn.Linear(120, 100)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x


vec_block = vecBlock().to(device)
print(vec_block)
vec_block(b_vec.to(device)).shape

"""### 整体模型构建"""

# Define model
class bigModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.img_block = ImageBlock()
        self.text_block = textCNN()
        self.vec_block = vecBlock()
        self.relu = nn.ReLU()
        self.lin1 = nn.Linear(300, 50)
        self.lin2 = nn.Linear(50, n_class)


    def forward(self, img,text,vec):
        x1 = self.img_block(img)
        x2 = self.text_block(text)
        x3 = self.vec_block(vec)

        x = torch.cat([x1,x2,x3],dim=1)
        x = self.flatten(x)
        x = self.lin1(x)
        x = self.lin2(x)
        # x =
        return x
big_model = bigModel().to(device)
big_model(b_img.to(device),b_text.to(device),b_vec.to(device)).shape





"""## 准备损失函数和优化器"""

loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
optimizer = torch.optim.Adam(big_model.parameters(), lr=2e-5)

"""## 训练和测试"""

epochs = 3
train_loss_list = []
train_acc_list = []
test_loss_list = []
test_acc_list = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dl, big_model, loss_fn, optimizer)

    train_loss, train_correct = test(train_dl, big_model, loss_fn)
    test_loss, test_correct = test(test_dl, big_model, loss_fn)
    train_loss_list.append(train_loss)
    train_acc_list.append(train_correct)
    test_loss_list.append(test_loss)
    test_acc_list.append(test_correct)
print("Done!")



"""## 可视化训练过程"""

# train_loss_array,train_acc_array,val_loss_array,val_acc_array
acc = train_acc_list
val_acc = test_acc_list

loss = train_loss_list
val_loss = test_loss_list
epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""## 统计指标分析"""



"""### 模型验证集预测"""

predict_list = []
label_list = []
predict_pro_list = []
m_softmax = nn.Softmax(dim=1)
for x_img, x_text, x_vec,  y in test_dl:
  x_img, x_text,x_vec,  y = x_img.to(device),x_text.to(device), x_vec.to(device),y.to(device)

  # Compute prediction error
  # print(x_img.shape,x_text.shape)
  predict_score = big_model(x_img, x_text, x_vec)
  # predict_score = big_model(b_img,b_text)
  predict_pro = m_softmax(predict_score)

  predict_label = np.argmax(predict_score.detach().cpu().numpy(),axis=1)

  predict_pro_list.append(predict_pro.detach().cpu().numpy())
  predict_list.append(predict_label)
  label_list.append(y.detach().cpu().numpy())

predict_pro_array = np.vstack(predict_pro_list)[:,1]
predict_array = np.hstack(predict_list)
label_array = np.hstack(label_list)
predict_pro_array[:5],predict_array[:5],label_array[:5]

np.unique(predict_array)

len(np.unique(label_array))



"""### 分类报告"""

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(label_array, predict_array,digits=3))



"""### 混淆矩阵"""



from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(label_array, predict_array)
cnf_matrix



sns.heatmap(cnf_matrix, annot=True, fmt='g')

cm_normalized = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_normalized, annot=True, fmt='.3f')





"""# 消融实验3： vit + bert + att + res"""



"""## 准备训练和测试循环"""



def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (x_img,x_img_clip, x_text,x_text_clip, x_vec, y) in enumerate(dataloader):

        x_img, x_text, y = x_img.to(device),x_text.to(device), y.to(device)
        x_img_clip,x_text_clip = x_img_clip.to(device),x_text_clip.to(device)
        x_vec = x_vec.to(device)
        pred = model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 30 == 0:
            loss, current = loss.item(), batch * len(x_img)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for batch, (x_img,x_img_clip, x_text,x_text_clip, x_vec,  y) in enumerate(dataloader):
            x_img, x_text, y = x_img.to(device),x_text.to(device), y.to(device)
            x_img_clip,x_text_clip = x_img_clip.to(device),x_text_clip.to(device)
            x_vec = x_vec.to(device)
            pred = model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss, correct

"""## 数据处理和特征工程"""





"""### 英文编码tokenizer roberta"""

model_name = "bert-base-chinese"
tokenizer_bert = AutoTokenizer.from_pretrained(model_name)



eg_text = '早上好'
eg_result = tokenizer_bert(eg_text, padding='max_length', max_length=25, truncation=True, return_tensors="pt")
eg_result

voc_size = tokenizer_bert.vocab_size
voc_size



"""### clip 文本处理"""

from transformers import AutoTokenizer, CLIPTextModelWithProjection

t_clip_model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
t_clip_tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

# inputs = t_clip_tokenizer(["a photo of a cat", "a photo of a dog"],  return_tensors="pt",max_length=50,padding="max_length",truncation=True)
inputs = t_clip_tokenizer("a photo of a cat",  return_tensors="pt",max_length=50,padding="max_length",truncation=True)

outputs = t_clip_model(**inputs)
text_embeds = outputs.text_embeds

text_embeds.shape



inputs

t_clip_model(inputs.input_ids).text_embeds

"""### clip 图像处理"""

from PIL import Image
import requests
from transformers import AutoProcessor, CLIPVisionModelWithProjection

img_clip_model = CLIPVisionModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
img_clip_processor = AutoProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = img_clip_processor(images=image, return_tensors="pt")

outputs = img_clip_model(**inputs)
image_embeds = outputs.image_embeds

inputs.pixel_values.shape

outputs.image_embeds.shape

pd_all.head()

"""### 准备dataset"""

class CustomDataset(Dataset):
    def __init__(self, pd_data,tokenizer_en):
        self.pd_data = pd_data
        self.text_list = list(pd_data['text'])
        self.label_list = list(pd_data['label'])
        self.img_path_list = list(pd_data['pic_path'])
        self.vec_lists = list(pd_data['vec'])
        self.tokenizer = tokenizer_en
        self.t_clip_tokenizer = t_clip_tokenizer
        self.img_clip_processor = img_clip_processor

    def __len__(self):
        return len(self.pd_data)

    def __getitem__(self, idx):


        # 文本数据处理
        one_text = self.text_list[idx]
        one_text_array = self.tokenizer(one_text, padding='max_length', max_length=max_len, truncation=True, return_tensors="pt")['input_ids'][0]
        one_clip_text = self.t_clip_tokenizer(one_text,  return_tensors="pt",max_length=max_len,padding="max_length",truncation=True)['input_ids'][0]


        # 图像数据处理
        one_path = self.img_path_list[idx]
        # one_path = img_dir + one_path
        img_tensor = read_image(one_path,mode=torchvision.io.ImageReadMode.RGB)
        img_tensor = transforms.Resize((224,224))(img_tensor).float()

        image = Image.open(one_path).convert("RGB")
        one_clip_img = img_clip_processor(images=image, return_tensors="pt").pixel_values[0]


        # 向量数据处理
        one_vec = self.vec_lists[idx]
        one_vec_tensor = torch.tensor(one_vec).float()


        # label数据处理
        one_label = self.label_list[idx]
        one_label = torch.tensor(one_label).long()
        return img_tensor, one_clip_img, one_text_array, one_clip_text, one_vec_tensor, one_label


tran_ds = CustomDataset(pd_train[:train_num],tokenizer_bert)
test_ds = CustomDataset(pd_test[:test_num],tokenizer_bert)

tran_ds[1][0].shape,tran_ds[1][1].shape,len(tran_ds),len(test_ds)

"""### 准备dataloader"""



train_dl = DataLoader(tran_ds, batch_size=10, shuffle=True)
test_dl = DataLoader(test_ds, batch_size=8)

len(test_dl.dataset)

for b_img,b_img_clip, b_text,b_text_clip,b_vec,label in test_dl:
  print(b_text.shape)
  print(b_img.shape)
  print(b_text_clip.shape)
  print(b_img_clip.shape)
  print(b_vec.shape)
  print(label)
  break

b_vec

"""## 模型构建

### vit模块
"""

class Image_vit(nn.Module):
    def __init__(self):
        super().__init__()
        self.base_model_vit = models.vit_b_16(pretrained=True)
        self.base_model_vit.heads.head = nn.Linear(768, 100)

    def forward(self, x):
        x = self.base_model_vit(x)
        return x

vit_block = Image_vit().to(device)
# print(img_block)
vit_block(b_img.to(device)).shape

"""### 文本数据处理"""



class textBert(nn.Module):
    def __init__(self,):
        super().__init__()
        self.model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=100).to(device)

    def forward(self, x):
        x = self.model(x)
        return x.logits
text_bert = textBert().to(device)

text_bert(b_text.to(device)).shape

"""### 结构化数据处理"""

class vecBlock(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3, 120)
        self.fc2 = nn.Linear(120, 100)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x


vec_block = vecBlock().to(device)
print(vec_block)
vec_block(b_vec.to(device)).shape

"""### 整体模型构建"""

# Define model
class bigModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.img_block = Image_vit()
        self.text_block = textBert()
        self.vec_block = vecBlock()

        self.img_clip_model = img_clip_model
        self.t_clip_model = t_clip_model
        self.relu = nn.ReLU()
        self.lin1 = nn.Linear(400, 50)
        self.lin2 = nn.Linear(50, n_class)
        self.lin_t = nn.Linear(512, 100)
        self.lin_i = nn.Linear(512, 100)
        self.att = nn.TransformerEncoderLayer(d_model=100,nhead=2)

    def forward(self, img,img_clip,text,text_clip,vec):
        x1 = self.img_block(img)
        # x4_img_clip = self.img_clip_model(img_clip).image_embeds
        # x4_img_clip = self.lin_i(x4_img_clip)

        x2 = self.text_block(text)
        # x5_t_clip = self.t_clip_model(text_clip).text_embeds
        # x5_t_clip = self.lin_t(x5_t_clip)

        x3 = self.vec_block(vec)

        x = torch.stack([x1,x2,x3],dim=1)
        x = self.att(x)

        x = self.flatten(x)

        x = torch.cat([x,x1],dim=1)
        x = self.lin1(x)
        x = self.lin2(x)
        # x =
        return x
big_model = bigModel().to(device)
big_model(b_img.to(device),b_img_clip.to(device),b_text.to(device),b_text_clip.to(device),b_vec.to(device)).shape





"""## 准备损失函数和优化器"""

loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
optimizer = torch.optim.Adam(big_model.parameters(), lr=2e-5)

"""## 训练和测试"""

epochs = 3
train_loss_list = []
train_acc_list = []
test_loss_list = []
test_acc_list = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dl, big_model, loss_fn, optimizer)

    train_loss, train_correct = test(train_dl, big_model, loss_fn)
    test_loss, test_correct = test(test_dl, big_model, loss_fn)
    train_loss_list.append(train_loss)
    train_acc_list.append(train_correct)
    test_loss_list.append(test_loss)
    test_acc_list.append(test_correct)
print("Done!")



"""## 可视化训练过程"""

# train_loss_array,train_acc_array,val_loss_array,val_acc_array
acc = train_acc_list
val_acc = test_acc_list

loss = train_loss_list
val_loss = test_loss_list
epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""## 统计指标分析"""



"""### 模型验证集预测"""

predict_list = []
label_list = []
predict_pro_list = []
m_softmax = nn.Softmax(dim=1)
for x_img,x_img_clip, x_text,x_text_clip, x_vec,  y in test_dl:
  x_img,x_img_clip, x_text,x_text_clip,x_vec,  y = x_img.to(device),x_img_clip.to(device),x_text.to(device),x_text_clip.to(device), x_vec.to(device), y.to(device)

  # Compute prediction error
  # print(x_img.shape,x_text.shape)
  predict_score = big_model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
  # predict_score = big_model(b_img,b_text)
  predict_pro = m_softmax(predict_score)

  predict_label = np.argmax(predict_score.detach().cpu().numpy(),axis=1)

  predict_pro_list.append(predict_pro.detach().cpu().numpy())
  predict_list.append(predict_label)
  label_list.append(y.detach().cpu().numpy())

predict_pro_array = np.vstack(predict_pro_list)[:,1]
predict_array = np.hstack(predict_list)
label_array = np.hstack(label_list)
predict_pro_array[:5],predict_array[:5],label_array[:5]

np.unique(predict_array)

len(np.unique(label_array))



"""### 分类报告"""

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(label_array, predict_array,digits=3))



"""### 混淆矩阵"""



from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(label_array, predict_array)
cnf_matrix



sns.heatmap(cnf_matrix, annot=True, fmt='g')

cm_normalized = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_normalized, annot=True, fmt='.3f')









"""# 消融实验4： vit + bert + att"""



"""## 准备训练和测试循环"""



def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (x_img,x_img_clip, x_text,x_text_clip, x_vec, y) in enumerate(dataloader):

        x_img, x_text, y = x_img.to(device),x_text.to(device), y.to(device)
        x_img_clip,x_text_clip = x_img_clip.to(device),x_text_clip.to(device)
        x_vec = x_vec.to(device)
        pred = model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 30 == 0:
            loss, current = loss.item(), batch * len(x_img)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for batch, (x_img,x_img_clip, x_text,x_text_clip, x_vec,  y) in enumerate(dataloader):
            x_img, x_text, y = x_img.to(device),x_text.to(device), y.to(device)
            x_img_clip,x_text_clip = x_img_clip.to(device),x_text_clip.to(device)
            x_vec = x_vec.to(device)
            pred = model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss, correct

"""## 数据处理和特征工程"""





"""### 英文编码tokenizer roberta"""

model_name = "bert-base-chinese"
tokenizer_bert = AutoTokenizer.from_pretrained(model_name)



eg_text = '早上好'
eg_result = tokenizer_bert(eg_text, padding='max_length', max_length=25, truncation=True, return_tensors="pt")
eg_result

voc_size = tokenizer_bert.vocab_size
voc_size



"""### clip 文本处理"""

from transformers import AutoTokenizer, CLIPTextModelWithProjection

t_clip_model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
t_clip_tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

# inputs = t_clip_tokenizer(["a photo of a cat", "a photo of a dog"],  return_tensors="pt",max_length=50,padding="max_length",truncation=True)
inputs = t_clip_tokenizer("a photo of a cat",  return_tensors="pt",max_length=50,padding="max_length",truncation=True)

outputs = t_clip_model(**inputs)
text_embeds = outputs.text_embeds

text_embeds.shape



inputs

t_clip_model(inputs.input_ids).text_embeds

"""### clip 图像处理"""

from PIL import Image
import requests
from transformers import AutoProcessor, CLIPVisionModelWithProjection

img_clip_model = CLIPVisionModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")
img_clip_processor = AutoProcessor.from_pretrained("openai/clip-vit-base-patch32")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

inputs = img_clip_processor(images=image, return_tensors="pt")

outputs = img_clip_model(**inputs)
image_embeds = outputs.image_embeds

inputs.pixel_values.shape

outputs.image_embeds.shape

pd_all.head()

"""### 准备dataset"""

class CustomDataset(Dataset):
    def __init__(self, pd_data,tokenizer_en):
        self.pd_data = pd_data
        self.text_list = list(pd_data['text'])
        self.label_list = list(pd_data['label'])
        self.img_path_list = list(pd_data['pic_path'])
        self.vec_lists = list(pd_data['vec'])
        self.tokenizer = tokenizer_en
        self.t_clip_tokenizer = t_clip_tokenizer
        self.img_clip_processor = img_clip_processor

    def __len__(self):
        return len(self.pd_data)

    def __getitem__(self, idx):


        # 文本数据处理
        one_text = self.text_list[idx]
        one_text_array = self.tokenizer(one_text, padding='max_length', max_length=max_len, truncation=True, return_tensors="pt")['input_ids'][0]
        one_clip_text = self.t_clip_tokenizer(one_text,  return_tensors="pt",max_length=max_len,padding="max_length",truncation=True)['input_ids'][0]


        # 图像数据处理
        one_path = self.img_path_list[idx]
        # one_path = img_dir + one_path
        img_tensor = read_image(one_path,mode=torchvision.io.ImageReadMode.RGB)
        img_tensor = transforms.Resize((224,224))(img_tensor).float()

        image = Image.open(one_path).convert("RGB")
        one_clip_img = img_clip_processor(images=image, return_tensors="pt").pixel_values[0]


        # 向量数据处理
        one_vec = self.vec_lists[idx]
        one_vec_tensor = torch.tensor(one_vec).float()


        # label数据处理
        one_label = self.label_list[idx]
        one_label = torch.tensor(one_label).long()
        return img_tensor, one_clip_img, one_text_array, one_clip_text, one_vec_tensor, one_label


tran_ds = CustomDataset(pd_train[:train_num],tokenizer_bert)
test_ds = CustomDataset(pd_test[:test_num],tokenizer_bert)

tran_ds[1][0].shape,tran_ds[1][1].shape,len(tran_ds),len(test_ds)

"""### 准备dataloader"""



train_dl = DataLoader(tran_ds, batch_size=10, shuffle=True)
test_dl = DataLoader(test_ds, batch_size=8)

len(test_dl.dataset)

for b_img,b_img_clip, b_text,b_text_clip,b_vec,label in test_dl:
  print(b_text.shape)
  print(b_img.shape)
  print(b_text_clip.shape)
  print(b_img_clip.shape)
  print(b_vec.shape)
  print(label)
  break

b_vec

"""## 模型构建

### vit模块
"""

class Image_vit(nn.Module):
    def __init__(self):
        super().__init__()
        self.base_model_vit = models.vit_b_16(pretrained=True)
        self.base_model_vit.heads.head = nn.Linear(768, 100)

    def forward(self, x):
        x = self.base_model_vit(x)
        return x

vit_block = Image_vit().to(device)
# print(img_block)
vit_block(b_img.to(device)).shape

"""### 文本数据处理"""



class textBert(nn.Module):
    def __init__(self,):
        super().__init__()
        self.model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=100).to(device)

    def forward(self, x):
        x = self.model(x)
        return x.logits
text_bert = textBert().to(device)

text_bert(b_text.to(device)).shape

"""### 结构化数据处理"""

class vecBlock(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3, 120)
        self.fc2 = nn.Linear(120, 100)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x


vec_block = vecBlock().to(device)
print(vec_block)
vec_block(b_vec.to(device)).shape

"""### 整体模型构建"""

# Define model
class bigModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.img_block = Image_vit()
        self.text_block = textBert()
        self.vec_block = vecBlock()

        self.img_clip_model = img_clip_model
        self.t_clip_model = t_clip_model
        self.relu = nn.ReLU()
        self.lin1 = nn.Linear(300, 50)
        self.lin2 = nn.Linear(50, n_class)
        self.lin_t = nn.Linear(512, 100)
        self.lin_i = nn.Linear(512, 100)
        self.att = nn.TransformerEncoderLayer(d_model=100,nhead=2)

    def forward(self, img,img_clip,text,text_clip,vec):
        x1 = self.img_block(img)
        # x4_img_clip = self.img_clip_model(img_clip).image_embeds
        # x4_img_clip = self.lin_i(x4_img_clip)

        x2 = self.text_block(text)
        # x5_t_clip = self.t_clip_model(text_clip).text_embeds
        # x5_t_clip = self.lin_t(x5_t_clip)

        x3 = self.vec_block(vec)

        x = torch.stack([x1,x2,x3],dim=1)
        x = self.att(x)

        x = self.flatten(x)

        # x = torch.cat([x,x1],dim=1)
        x = self.lin1(x)
        x = self.lin2(x)
        # x =
        return x
big_model = bigModel().to(device)
big_model(b_img.to(device),b_img_clip.to(device),b_text.to(device),b_text_clip.to(device),b_vec.to(device)).shape





"""## 准备损失函数和优化器"""

loss_fn = nn.CrossEntropyLoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
optimizer = torch.optim.Adam(big_model.parameters(), lr=2e-5)

"""## 训练和测试"""

epochs = 3
train_loss_list = []
train_acc_list = []
test_loss_list = []
test_acc_list = []
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dl, big_model, loss_fn, optimizer)

    train_loss, train_correct = test(train_dl, big_model, loss_fn)
    test_loss, test_correct = test(test_dl, big_model, loss_fn)
    train_loss_list.append(train_loss)
    train_acc_list.append(train_correct)
    test_loss_list.append(test_loss)
    test_acc_list.append(test_correct)
print("Done!")



"""## 可视化训练过程"""

# train_loss_array,train_acc_array,val_loss_array,val_acc_array
acc = train_acc_list
val_acc = test_acc_list

loss = train_loss_list
val_loss = test_loss_list
epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""## 统计指标分析"""



"""### 模型验证集预测"""

predict_list = []
label_list = []
predict_pro_list = []
m_softmax = nn.Softmax(dim=1)
for x_img,x_img_clip, x_text,x_text_clip, x_vec,  y in test_dl:
  x_img,x_img_clip, x_text,x_text_clip,x_vec,  y = x_img.to(device),x_img_clip.to(device),x_text.to(device),x_text_clip.to(device), x_vec.to(device), y.to(device)

  # Compute prediction error
  # print(x_img.shape,x_text.shape)
  predict_score = big_model(x_img,x_img_clip, x_text,x_text_clip, x_vec)
  # predict_score = big_model(b_img,b_text)
  predict_pro = m_softmax(predict_score)

  predict_label = np.argmax(predict_score.detach().cpu().numpy(),axis=1)

  predict_pro_list.append(predict_pro.detach().cpu().numpy())
  predict_list.append(predict_label)
  label_list.append(y.detach().cpu().numpy())

predict_pro_array = np.vstack(predict_pro_list)[:,1]
predict_array = np.hstack(predict_list)
label_array = np.hstack(label_list)
predict_pro_array[:5],predict_array[:5],label_array[:5]

np.unique(predict_array)

len(np.unique(label_array))



"""### 分类报告"""

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(label_array, predict_array,digits=3))



"""### 混淆矩阵"""



from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(label_array, predict_array)
cnf_matrix



sns.heatmap(cnf_matrix, annot=True, fmt='g')

cm_normalized = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_normalized, annot=True, fmt='.3f')





